# Generated by Django 5.1.2 on 2024-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0002_initial'),
    ]

    operations = [
    ]
