# Generated by Django 5.1.2 on 2024-11-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0003_auto_20241106_1917'),
    ]

    operations = [
    ]
