# Generated by Django 5.1.2 on 2024-11-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0004_auto_20241106_1931'),
    ]

    operations = [
    ]
