# Generated by Django 5.1.2 on 2024-11-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0005_auto_20241106_1958'),
    ]

    operations = [
    ]
