# Generated by Django 5.1.2 on 2024-11-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0006_auto_20241106_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(),
        ),
    ]
