# Generated by Django 5.1.2 on 2024-11-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_servidor', '0007_alter_producto_cantidad_disponible'),
    ]

    operations = [
    ]
