name: Ejecutar servidor Django

on:
  push:
    branches:
      - main

jobs:
  runserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run server
        env:
          DJANGO_SETTINGS_MODULE: "my_servidor.settings"
        run: |
          python manage.py migrate
          python manage.py runserver
